### ISSUE TITLE
Custom interfaces have first letter of name cutoff

### ISSUE THREAD

**Issue by carsonfarmer** [sue71/protoc-gen-jsonpb-ts#17]
Here's an example:

Proto:

```
message Contact {
    string address      = 1;
    string name         = 2;
    string avatar       = 3;
}

message ContactList {
    repeated Contact items = 1;
}

```

Generated interface (should be `Contact[]` not `ontact[]`):

```
export interface Contact {
  address?: string;
  name?: string;
  avatar?: string;
}

export interface ContactList {
  items?: ontact[];
}
```

Looks like its coming [from here](https://github.com/sue71/protoc-gen-jsonpb-ts/blob/b15aceee009601cf8487f98e4877c8f97b73ff22/src/utils.ts#L59)?

**Comment by carsonfarmer** [comment]
Oops, I was wrong, the issue is actually with [this method](https://github.com/sue71/protoc-gen-jsonpb-ts/blob/master/src/ts/helper.ts#L101).

**Comment by sue71** [comment]
@carsonfarmer 
Thank you for reporting 👍  I confirmed that the same behavior would occur if no package was specified in the proto file.

**Comment by carsonfarmer** [comment]
Awesome, thanks for taking a look at this, and thanks for the quick fix 👍
